# Coroutine Scope 함수

- 여러 개의 endpoint에서 데이터를 동시에 얻어야 하는 중단 함수를 떠올려보자.  
  가장 바람직한 방법을 보기 전, 차선책부터 살펴보자.

## 코루틴 scope 함수가 소개되기 전 사용한 방법들

- 첫 번째 방법은 중단 함수에서 중단 함수를 호출하는 것이다. 문제는 작업이 동시에 진행되지 않는다는 점이다.

```kt
// 데이터를 동시에 가져오지 않고, 순차적으로 가져온다
suspend fun getUserProfile(): UserProfileData {
	val user = getUserData() // 1초
	val notifications = getNotifications() // 1초
	return UserProfileData(
		user = user,
		notifications = notifications
	)
}
```

- 두 개의 중단 함수를 동시에 실행하려면 각각 `async()` 로 wrapping해야 한다.  
  하지만 `async()` 는 scope를 필요로 하며, `GlobalScope` 를 사용하는 것은 좋은 방법이 아니다.

```kt
// 이렇게 구현하면 안된다.
suspend fun getUserProfile(): UserProfileData {
	val user = GlobalScope.async { getUserData() }
	val notifications = GlobalScope.async { getNotifications() }
	return UserProfileData(
		user = user.await(), // 1초
		notifications = notifications.await()
	)
}
```

- `GlobalScope`는 그저 `EmptyCoroutineContext` 를 가진 scope일 뿐이다.

```kt
public object GlobalScope : CoroutineScope {
	override val coroutineContext : CoroutineContext
		get() = EmptyCoroutineContext
}
```

- `GlobalScope` 에서 `async()` 를 호출하면 부모 코루틴과 아무런 관계가 없다. 이때 `async()` 코루틴은

  - 취소될 수 없다.
  - 부모가 취소되어도 `async()` 내부의 함수가 실행 중인 상태가 되므로, 작업이 끝날 때까지 자원이 낭비된다.
  - 부모로부터 scope를 상속받지 않는다.
  - 항상 기본 dispatcher에서 실행되며, 부모의 context를 전혀 신경쓰지 않는다.

- 가장 중요한 결과는 아래와 같다.

  - 메모리 누수가 발생할 수 있으며, 쓸데없이 CPU를 낭비한다.
  - 코루틴을 단위 테스트하는 도구가 작동하지 않아, 함수를 테스트하기 어렵다.

- 따라서 위와 같은 방법은 전혀 좋다고 할 수 없다. Scope를 인자로 넘기는 다음 방법을 보자.

```kt
// 이렇게 구현하면 안된다.
suspend fun getUserProfile(scope: CoroutineScope): UserProfileData {
	val user = scope.async { getUserData() }
	val notifications = scope.async { getNotifications() }

	return UserProfileData(
		user = user.await(),
		notifications = notifications.await()
	)
}
```

- 이 방법은 취소가 가능하고, 적절한 단위 테스트를 추가할 수 있는 방식이라는 점에서 좀 더 낫다고 할 수 있다.  
  문제는 scope가 함수에서 함수로 전달되어야 한다는 것이다.  
  Scope가 함수로 전달되면, scope에서 예상하지 못한 부작용이 발생할 수 있다.  
  예를 들어, `async()` 에서 예외가 발생하면 모든 scope가 닫히게 된다. (`SupervisorJob`이 아니라 가정)  
  또한, scope에 접근하는 함수가 `cancel()` 을 통해 scope를 취소하는 등 scope를 조작할 수도 있다.  
  따라서 이런 접근 방식은 다루기 어려울 뿐만 아니라, 잠재적으로 위험하다고 볼 수 있다.

```kt
data class Details(val name: String, val followers: Int)
data class Tweet(val text: String)

fun getFollowersNumber(): Int = throw Error("Service exception")

suspend fun getUserName(): String {
	delay(500)
	return "sangwoo"
}

suspend fun getTweets(): List<Tweet> {
	return listOf(Tweet("Hi"))
}

suspend fun CoroutineScope.getUserDetails(): Details {
	val userName = async { getUserName() }
	val followersNumber = async { getFollowersNumber() }
	return Details(userName.await(), followersNumber.await())
}

fun main() = runBlocking {
	val details = try {
		getUserDetails()
	} catch (e: Error) {
		null
	}
	val tweets = async { getTweets() }
	println("User: $details")
	println("Tweets: ${tweets.await()}")
}
```

- 위 코드를 보면 user detail을 들고 오는 데 문제가 있더라도, 최소한 tweet은 볼 수 있을 것 같다.  
  하지만 `getFollowersNumber()` 에서 발생한 예외가 `async()` 를 종료시키고,  
  전체 scope가 종료되는 것으로 이어져 프로그램이 종료되어버린다.  
  예외가 발생하면 종료되는 대신, 예외를 그대로 던지는 함수가 더 낫다. 여기서 `coroutineScope()` 가 등장한다.

---

## `coroutineScope()`

- `coroutineScope()` 는 scope를 시작하는 중단 함수이며, 인자로 들어온 함수가 생성한 값을 반환한다.

```kt
suspend fun <R> coroutineScope(
	block: suspend CoroutineScope.() -> R
): R
```

- `async()` 나 `launch()` 와는 달리, `coroutineScope()` 의 본체는 receiver 없이 곧바로 호출된다.  
  `coroutineScope()` 는 새로운 코루틴을 생성하지만, 새로운 코루틴이 끝날 때까지 `coroutineScope()` 를  
   호출한 코루틴을 중단시키기 때문에 호출한 코루틴이 작업을 동시에 시작하지는 않는다.

- 두 `delay()` 호출 모두 `runBlocking()` 을 중단시키는 아래 예를 보자.

```kt
fun main() = runBlocking {
	val a = coroutineScope {
		delay(1000)
		10
	}
	println("a is calculated")
	val b = coroutineScope {
		delay(1000)
		20
	}
	println(a) // 10
	println(b) // 20
}

// (1초 후)
// a is calculated
// (1초 후)
// 10
// 20
```

- 생성된 scope는 바깥의 scope에서 `CoroutineContext` 를 상속받지만, context의 `Job`을 overriding한다.  
  따라서 생성된 scope는 부모가 해야 할 책임을 이어받는다.

  - 부모로부터 context를 상속받는다.
  - 자신의 작업을 끝내기 전까지 모든 자식을 기다린다.
  - 부모가 취소되면 자식들 모두를 취소한다.

- 아래 예시에서는 `coroutineScope()` 이 모든 자식이 끝날 때까지 종료되지 않으므로 `"After"` 가  
  마지막에 출력되는 것을 확인할 수 있다. 또한 `CoroutineName` 이 부모에서 자식으로 전달되는 것도 확인할 수 있다.

```kt
suspend fun longTask() = coroutineScope {
	launch {
		delay(1000)
		val name = coroutineContext[CoroutineName]?.name
		println("[$name] Finished task 1")
	}
	launch {
		delay(2000)
		val name = coroutineContext[CoroutineName]?.name
		println("[$name] Finished task 2")
	}
}

fun main() = runBlocking(CoroutineName("Parent")) {
	println("Before")
	longTask()
	println("After")
}

// Before
// (1초 후)
// [Parent] Finished task 1
// (1초 후)
// [Parent] Finished task 2
// After
```

- 아래 코드에서는 취소의 동작 방식을 볼 수 있다. 부모가 취소되면, 아직 끝나지 않은 자식 코루틴이 전부 취소된다.

```kt
suspend fun longTask() = coroutineScope {
	launch {
		delay(1000)
		val name = coroutineContext[CoroutineName]?.name
		println("[$name] Finished task 1")
	}
	launch {
		delay(2000)
		val name = coroutineContext[CoroutineName]?.name
		println("[$name] Finished task 2")
	}
}

fun main(): Unit = runBlocking {
	val job = launch(CoroutineName("Parent")) {
		longTask()
	}
	delay(1500)
	job.cancel()
}

// [Parent] Finished task 1
```

- 코루틴 빌더와 달리 `coroutineScope()` 나 scope 내에 속한 자식에서 예외가 발생하면, 다른 모든 자식이 취소되고 예외가 다시 던져진다.

```kt
data class Details(val name: String, val followers: Int)
data class Tweet(val text: String)
class ApiException(val code: Int, message: String): Throwable(message)

fun getFollowersNumber(): Int = throw ApiException(500, "Service unavailable")

suspend fun getUserName(): String {
	delay(500)
	return "Sangwoo"
}

suspend fun getTweets(): List<Tweet> {
	return listOf(Tweet("hi"))
}

suspend fun getUserDetails(): Details = coroutineScope {
	val userName = async { getUserName() }
	val followersNumber = async { getFollowersNumber() }
	Details(userName.await(), followersNumber.await())
}

fun main() = runBlocking {
	val details = try {
		getUserDetails()
	} catch(e: ApiException) {
		null
	}
	val tweets = async { getTweets() }
	println("User: $details")
	println("Tweets: ${tweets.await()}")
}

// User: null
// Tweets: [Tweet(text = hi)]
```

- 위에서 본 것처럼 `coroutineScope()` 는 중단 메인 함수 본체를 wrapping할 때 주로 사용된다.

```kt
suspend fun main(): Unit = coroutineScope {
	launch {
		delay(1000)
		println("2")
	}
	println("1")
}

// 1
// (1초 후)
// 2
```

- `coroutineScope()` 는 기존의 중단 context에서 벗어난 새로운 scope를 생성한다.  
  부모로부터 scope를 상속받고, 구조화된 동시성을 지원한다.
- 아래 함수들은 첫 번째 함수가 `getProfile()` 과 `getFriends()` 를 연속으로 호출하고,  
  두 번째 함수는 함수를 병렬로 호출한다는 점을 제외하면 사용하는 면에서는 차이가 없다.

```kt
suspend fun produceCurrentUserSeq(): User {
	val profile = repo.getProfile()
	val friends = repo.getFriends()
	return User(profile, friends)
}

suspend fun produceCurrentUserSym(): User = coroutineScope {
	val profile = async { repo.getProfile() }
	val friends = async { repo.getFriends() }
	User(profile.await(), friends.await())
}
```

- `coroutineScope()`는 유용한 함수이지만, scope를 만드는 함수는 이것 말고도 여러가지가 있다.

---

## 코루틴 scope 함수

- Scope를 만드는 다양한 함수가 있으며, `coroutineScope()` 와 비슷하게 동작한다.  
  `supervisorScope()` 는 `coroutineScope()` 와 비슷하지만, `Job` 대신 `SupervisorJob`을 사용한다.  
  `withContext()`는 코루틴 context를 바꿀 수 있는 `coroutineScope()` 이다.  
  `withTimeout()` 은 timeout이 있는 `coroutineScope()` 이다. 이 함수들은 뒷 부분에서 더 자세히 다룬다.  
  지금 당장은 코루틴 scope를 만들 수 있는 다양한 함수들이 존재한다는 것만 알면 된다.  
  여기서는 이런 함수들을 통틀어 “코루틴 scope 함수” 라고 지칭할 것이다.

- 코루틴 scope 함수는 코루틴 빌더와 혼동되미나, 이 둘은 개념적으로나 사용함에 있어서나 전혀 다르기에 쉽게 구분할 수 있다.

  - 코루틴 빌더(`runBlocking()` 제외)
    - `launch()`, `async()`, `produce()`
    - `CoroutineScope` 의 확장 함수
    - `CoroutineScope` receiver의 코루틴 context 사용
    - 예외는 `Job` 을 통해 부모로 전파된다.
    - 비동기 코루틴을 시작한다.
  - 코루틴 scope 함수
    - `coroutineScope()`, `supervisorScope()`, `withContext()`, `withTimeout()`
    - 중단 함수
    - 중단 함수의 `Continuation` 객체가 가진 코루틴 context tkdyd
    - 일반 함수와 같이 예외를 throw
    - 코루틴 빌더가 호출된 곳에서 코루틴 시작

- 이제 `runBlocking()` 을 생각해보자.  
  `runBlocking()` 은 코루틴 빌더보다 코루틴 scope 함수와 비슷한 점이 더 많아보인다.  
  `runBlocking()` 또한 함수 본체를 곧바로 호출하고, 그 결과를 반환한다.  
  가장 큰 차이점은 `runBlocking()` 은 blocking 함수이지만, 코루틴 scope 함수는 중단 함수라는 것이다.  
  따라서 `runBlocking()` 은 코루틴의 계층에서 가장 상위에 있으며, 코루틴 scope 함수는 계층 중간에 있는 것이다.

---

## `withContext()`

- `withContext()` 는 `coroutineScope()` 와 비슷하지만 scope의 context를 변경할 수 있다는 점에서 다르다.  
  `withContext()` 의 인자로 context를 제공하면, 부모 scope의 context를 대체한다.  
  따라서 `withContext(EmptyCoroutineContext)` 와 `coroutineScope()` 는 정확히 동일하게 작동한다.

```kt
fun CoroutineScope.log(text: String) {
	val name = this.coroutineContext[CoroutineName]?.name
	println("[$name] $text")
}

fun main() = runBlocking(CoroutineName("Parent")) {
	log("Before")

	withContext(CoroutineName("Child 1")) {
		delay(1000)
		log("Hello 1")
	}

	withContext(CoroutineName("Child 2")) {
		delay(1000)
		log("Hello 2")
	}

	log("After")
}

// [Parent] Before
// (1초 후)
// [Child 1] Hello 1
// (1초 후)
// [Child 2] Hello 2
// [Parent] After
```

- `withContext()` 는 주로 기존 scope와 context가 다른 코루틴 scope를 설정하기 위해 사용된다.

---

## `supervisorScope()`

- `supervisorScope()` 는 호출한 scope로부터 상속받은 `CoroutineScope` 를 만들고,  
  지정된 중단 함수를 호출한다는 점에서 `coroutineScope()` 와 비슷하다.  
  둘의 차이는 context의 `Job` 을 `SupervisorJob` 으로 overriding한다는 것이기 때문에,  
  자식 코루틴이 예외를 던져도 취소되지 않는다.

```kt
fun main() = runBlocking {
	println("Before")

	supervisorScope {
		launch {
			delay(1000)
			throw Error()
		}

		launch {
			delay(2000)
			println("Done")
		}
	}
	println("After")
}

// Before
// (1초 후)
// (예외 발생)
// (1초 후)
// Done
// After
```

- `supervisorScope()` 는 서로 독립적인 작업을 시작하는 함수에서 주로 사용된다.

```kt
suspend fun notifyAnalytics(actions: List<UserAction>) =
	supervisorScope {
		actions.forEach { action ->
			launch { notifyAnalytics(action }
		}
	}
```

- `async()` 를 사용한다면 예외가 부모로 전파되는 것을 막는 것 외에 추가적인 예외 처리가 필요하다.  
  `await()` 을 호출하고 `async()` 코루틴이 예외로 끝나게 된다면, `await()` 는 다시 예외를 던지게 된다.  
  따라서 `async()` 에서 발생하는 예외를 전부 처리하려면 try-catch로 `async()` 의 호출을 wrapping해야 한다.

```kt
class ArticlesRepositoryComposite(
	private val articleRepositories: List<ArticleRepository>
): ArticleRepository {
	override suspend fun fetchArticles(): List<Article> =
		supervisorScope {
			articleRepositories
				.map { async { it.fetchArticles() } }
				.mapNotNull {
					try {
						it.await()
					} catch (e: Throwable) {
						e.printStackTrace()
						null
					}
				}
				.flatten()
				.sortedByDescending { it.publishedAt }
	}
}
```

- `supervisorScope()` 대신 `withContext(SupervisorJob())` 을 사용하면 안된다.  
  `withContext(SupervisorJob())` 을 사용하면, `withContext()` 는 여전히 기존에 가지고 있던  
  `Job` 을 사용하며, `SupervisorJob()` 이 해당 `Job` 의 부모가 된다.  
  따라서 하나의 자식 코루틴이 예외를 던진다면, 다른 자식들 또한 취소되게 된다.  
  `withContext()` 또한 예외를 던지기 때문에, `SupervisorJob()` 은 사실상 쓸모가 없게 된다.

---

## `withTimeout()`

- `coroutineScope()` 와 비슷한 또 다른 함수는 `withTimeout()` 이다. 이 함수 또한 scope를 만들고 값을 반환한다.  
  `withTimeout()` 에 아주 큰 timeout 값을 넣어주면 `coroutineScope()` 와 다를게 없다.  
  `withTimeout()` 은 인자로 들어온 lambda 식을 실행할 때 시간 제한이 있다는 점만 다르다.  
  실행하는 데 드는 시간이 지정한 시간을 초과하면 `CancellationException` 의 subtype인 `TimeoutCancellationException` 을 던진다.

```kt
suspend fun test(): Int = withTimeout(1500) {
	delay(1000)
	println("Still thinking")
	delay(1000)
	println("Done")
	42
}

suspend fun main() = coroutineScope {
	try {
		test()
	} catch(e: TimeoutCancellationException) {
		println("Cancelled")
	}
	delay(1000) // `test()` 가 취소되었기에 timeout 시간을 늘려도 도움이 되지 않는다.
}

// (1초 후)
// Still thinking
// (0.5초 후)
// Cancelled
```

- `withTimeout()` 은 특히 테스트할 때 유용하다. 특정 함수가 시간이 오래 혹은 적게 걸리는지 확인하는 테스트 용도로 사용된다.
- `withTimeout()` 이 `CancellationException` 의 subtype인 `TimeoutCancellationException` 을  
  던진다는 것은 중요하다. 코루틴 빌더 내부에서 `TimeoutCancellationException` 을 던지면  
  해당 코루틴만 취소가 되고, 부모에게는 영향을 주지 않는다.

```kt
suspend fun main() = coroutineScope {
	launch { // (1)
		launch { // (2) 부모에 의해 취소된다.
			delay(2000)
			println("Will not be printed")
		}
		withTimeout(1000) {
			delay(1500)
		}
	}

	launch { // (3)
		delay(2000)
		println("Done")
	}
}

// (2초 후)
// Done
```

- 위 예제에서 `delay(1500)` 은 `withTimeout(1000)` 보다 시간이 더 걸리므로  
  `TimeoutCancellationException` 을 던지게 된다. 예외는 `(1)` 의 `launch()` 에서 잡히며,  
  `(1)`에서 시작돤 코루틴과 `(2)` 의 `launch()` 로 시작된 자식 코루틴 또한 취소한다.  
  `(3)` 에서 시작된 `launch()` 에는 아무런 영향이 없다.
- `withTimeout()` 의 좀 더 완화된 형태의 함수인 `withTimeoutOrNull()` 은 예외를 던지는 대신,  
  timeout을 초과하면 lambda 식을 취소하고 null을 반환한다.

```kt
suspend fun fetchUser(): User {
	// 영원히 실행된다.
	while (true) {
		yield()
	}
}

suspend fun getUserOrNull(): User? =
	withTimeoutOrNull(5000) {
		fetchUser()
	}

suspend fun main(): Unit = coroutineScope {
	val user = getUserOrNull()
	println("User: $user")
}

// (5초 후)
// User: null
```

---

## 코루틴 scope 함수 연결하기

- 서로 다른 코루틴 scope 함수의 두 가지 기능이 모두 필요하다면, 코루틴 scope 함수에서 다른 기능을 가지는  
  코루틴 scope 함수를 호출해야 한다. Timeout과 dispatcher 둘 모두를 설정하면 `withContext()` 내부에서  
  `withTimeoutOrNull()` 을 사용할 수 있다.

```kt
suspend fun calculateAnswerOrNull(): User? =
	withContext(Dispatchers.Default) {
		withTimeoutOrNull(1000) {
			calculateAnswer()
		}
	}
```

---

## 추가적인 연산

- 작업을 수행하는 도중에 추가적인 연산을 수행하는 경우를 보자.
  예를 들어 사용자 프로필을 보여준 다음, 분석을 위한 목적으로 요청을 보내고 싶다고 해보자.
  이런 경우, 동일한 scope에서 `launch()` 를 호출하는 방법이 자주 사용된다.

```kt
class ShowUserDataUseCase(
	private val repo: UserDataRepository,
	private val view: UserDataView
) {
	suspend fun showUserData() = coroutineScope {
		val name = async { repo.getName() }
		val friends = async { repo.getFriends() }
		val profile = async { repo.getProfile() }
		val user = User(
			name = name.await(),
			friends = friends.await(),
			profile = profile.await()
		)
		view.show(user)
		launch { repo.notifyProfileShown() }
	}
}
```

- 하지만 이 방식에는 문제가 몇 가지 있다. 먼저 `coroutineScope()` 가 사용자 데이터를 보여준 뒤,  
  `launch()` 로 시작된 코루틴이 끝나기를 기다려야 하므로 `launch()` 에서 함수의 목적과 관련된  
  유의미한 작업을 한다고 보기 어렵다. View를 업데이트할 때 프로그레스 바를 보여주고 싶다면  
  `notifyProfileShown()` 이 끝날 때까지 기다려야 하는 꼴이다.  
  이 방식은 추가적인 연산을 처리하는 방식으로는 적절하지 못하다.

- 두 번째 문제는 취소이다. 코루틴은 기본적으로 예외가 발생했을 때 다른 연산을 취소하게 설계되어 있다.  
  필수적인 연산을 수행할 때 취소는 아주 유용하다. `getName()` 에서 예외가 발생하면  
  `getFriends()` 나 `getProfile()` 도 쓸모가 없어지기 때문에 취소가 되어야 한다.  
  하지만 분석을 위한 호출이 실패했다고 해서 전체 과정이 취소가 되는 것은 말도 안되는 일이다.

- 따라서 핵심 동작에 영향을 주지 않는 추가적인 연산이 있는 경우, 또 다른 scope에서 시작시키는 편이 낫다.  
  쉬운 방법은 추가적인 연산을 위한 scope를 만드는 것이다.

```kt
val analyticsScope = CoroutineScope(SupervisorJob())

class ShowUserDataUseCase(
	private val repo: UserDataRepository,
	private val view: UserDataView
) {
	suspend fun showUserData() = coroutineScope {
		val name = async { repo.getName() }
		val friends = async { repo.getFriends() }
		val profile = async { repo.getProfile() }
		val user = User(
			name = name.await(),
			friends = friends.await(),
			profile = profile.await()
		)
		view.show(user)
		analyticsScope.launch { repo.notifyProfileShown() }
	}
}
```

- 주입된 scope에서 추가적인 연산을 처리하게 하는 것은 자주 사용되는 방법이다.  
  Scope를 전달하면 전달된 클래스를 통해 독립적인 작업을 실행함을 명확하게 알 수 있다.  
  따라서 중단 함수는 주입된 scope에서 시작한 연산이 끝나기를 기다리지 않는다.  
  Scope가 전달되지 않으면 중단 함수는 모든 연산이 완료될 때까지 종료되지 않을 것이다.

---
